on:
  push:
    branches:
      - main 

name: release-please

jobs:
  release-please:
    if: github.repository_owner == 'COMBINE-lab'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: googleapis/release-please-action@v4
        id: release_main
        with:
          release-type: rust
          package-name: grangers
          bump-minor-pre-major: true
          path: .

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        if: ${{ steps.release_main.outputs.release_created }}

      - uses: Swatinem/rust-cache@v2
        if: ${{ steps.release_main.outputs.release_created }}

      - name: Publish grangers
        if: ${{ steps.release_main.outputs.release_created }}
        run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}
